### ISSUE TITLE
inner_join removes certain SBS signatures

### ISSUE THREAD

**Issue by wvandegeer** [J0bbie/R2CPCT#1]
There's a nifty little function called 'cleanSigs' in "R2CPCT/R/analysisWGS_fitMutSigs.R". 
The inner_join on line 135 chucks out SBS10c, SBS10d, SBS91, SBS92, SBS93 en SBS94:
`dplyr::inner_join(R2CPCT::proposedAetiologyCOSMICv3.1, by = 'Signature')`
This can lead to a relative contribution that does't add up to 100% (obviously only when there's any contribution from those signatures).

Proposed fix is either 
1. Expanding R2CPCT::proposedAetiologyCOSMICv3.1 with these signatures
2. Switching to dplyr::left_join.

**Comment by J0bbie** [comment]
Good point, I've implemented fix #2.
Should work as expected now.
